# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4
    hooks:
    -   id: ruff
        args: [--fix]
    -   id: ruff-format

-   repo: local
    hooks:
    -   id: update-requirements
        name: Update requirements.txt with pipreqs
        entry: pipreqs .
        language: system
        pass_filenames: false
        args: ["--force"]
    -   id: fix-sckit-import
        always_run: true
        name: fix sckit import
        entry: python3 scripts/fix_requirements.py
        language: python
        pass_filenames: false
    -   id: stage-requirements
        name: Stage requirements.txt
        entry: git
        args: ["add","requirements.txt"]
        language: system
        pass_filenames: false
    -   id: commit-requirements
        name: Commit requirements.txt
        entry: git
        args: ["commit", "-m", "updated automatically requirements.txt", "--no-verify"]
        language: system
        pass_filenames: false
